//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for MembershipStatus.
const (
	Active   MembershipStatus = "active"
	Inactive MembershipStatus = "inactive"
)

// Valid indicates whether the value is a known member of the MembershipStatus enum.
func (e MembershipStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// Book defines model for Book.
type Book struct {
	// Available Whether the Book is currently free to borrow.
	Available bool               `json:"available"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
}

// BookList defines model for BookList.
type BookList struct {
	Data []Book `json:"data"`

	// NextCursor Cursor for the next page, or null when exhausted.
	NextCursor *string `json:"next_cursor"`
}

// BorrowRequest defines model for BorrowRequest.
type BorrowRequest struct {
	// BookId The Book to borrow.
	BookId openapi_types.UUID `json:"book_id"`

	// MemberId The Member borrowing the Book.
	MemberId openapi_types.UUID `json:"member_id"`
}

// BorrowResult defines model for BorrowResult.
type BorrowResult struct {
	// DueDate The instant by which the Book must be returned.
	DueDate time.Time `json:"due_date"`

	// LoanId The identifier of the newly created Loan (UUID).
	LoanId string `json:"loan_id"`
}

// CreateBookRequest defines model for CreateBookRequest.
type CreateBookRequest struct {
	Title string `json:"title"`
}

// CreateMemberRequest defines model for CreateMemberRequest.
type CreateMemberRequest struct {
	Name string `json:"name"`
}

// Error The single error shape shared by every non-2xx response.
type Error struct {
	// Error A human-readable description of what went wrong.
	Error string `json:"error"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	// Status Example: ok
	Status string `json:"status"`
}

// Loan defines model for Loan.
type Loan struct {
	BookId     openapi_types.UUID `json:"book_id"`
	BorrowedAt time.Time          `json:"borrowed_at"`
	DueDate    time.Time          `json:"due_date"`
	Id         openapi_types.UUID `json:"id"`
	MemberId   openapi_types.UUID `json:"member_id"`

	// ReturnedAt When the Loan was returned; null while still active.
	ReturnedAt *time.Time `json:"returned_at,omitempty"`
}

// LoanList defines model for LoanList.
type LoanList struct {
	Data       []Loan  `json:"data"`
	NextCursor *string `json:"next_cursor"`
}

// Member defines model for Member.
type Member struct {
	// ActiveLoans The Member's current active-Loan count.
	ActiveLoans int                `json:"active_loans"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`

	// Status Whether a Member is currently entitled to borrow.
	Status MembershipStatus `json:"status"`
}

// MemberList defines model for MemberList.
type MemberList struct {
	Data       []Member `json:"data"`
	NextCursor *string  `json:"next_cursor"`
}

// MembershipStatus Whether a Member is currently entitled to borrow.
type MembershipStatus string

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// PathID defines model for PathID.
type PathID = openapi_types.UUID

// BadRequest The single error shape shared by every non-2xx response.
type BadRequest = Error

// Conflict The single error shape shared by every non-2xx response.
type Conflict = Error

// InternalError The single error shape shared by every non-2xx response.
type InternalError = Error

// NotFound The single error shape shared by every non-2xx response.
type NotFound = Error

// NotImplemented The single error shape shared by every non-2xx response.
type NotImplemented = Error

// UnprocessableEntity The single error shape shared by every non-2xx response.
type UnprocessableEntity = Error

// ListBooksParams defines parameters for ListBooks.
type ListBooksParams struct {
	// Limit Maximum number of items to return in one page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by a previous page as next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListLoansParams defines parameters for ListLoans.
type ListLoansParams struct {
	// Limit Maximum number of items to return in one page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by a previous page as next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListMembersParams defines parameters for ListMembers.
type ListMembersParams struct {
	// Limit Maximum number of items to return in one page.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by a previous page as next_cursor.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateBookJSONRequestBody defines body for CreateBook for application/json ContentType.
type CreateBookJSONRequestBody = CreateBookRequest

// BorrowBookJSONRequestBody defines body for BorrowBook for application/json ContentType.
type BorrowBookJSONRequestBody = BorrowRequest

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = CreateMemberRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListBooks List Books
	// (GET /books)
	ListBooks(w http.ResponseWriter, r *http.Request, params ListBooksParams)
	// CreateBook Create a Book
	// (POST /books)
	CreateBook(w http.ResponseWriter, r *http.Request)
	// GetBook Get a Book by identifier
	// (GET /books/{id})
	GetBook(w http.ResponseWriter, r *http.Request, id PathID)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// ListLoans List Loans
	// (GET /loans)
	ListLoans(w http.ResponseWriter, r *http.Request, params ListLoansParams)
	// BorrowBook Borrow a Book
	// (POST /loans)
	BorrowBook(w http.ResponseWriter, r *http.Request)
	// GetLoan Get a Loan by identifier
	// (GET /loans/{id})
	GetLoan(w http.ResponseWriter, r *http.Request, id PathID)
	// ReturnLoan Return a Loan
	// (POST /loans/{id}/return)
	ReturnLoan(w http.ResponseWriter, r *http.Request, id PathID)
	// ListMembers List Members
	// (GET /members)
	ListMembers(w http.ResponseWriter, r *http.Request, params ListMembersParams)
	// CreateMember Create a Member
	// (POST /members)
	CreateMember(w http.ResponseWriter, r *http.Request)
	// GetMember Get a Member by identifier
	// (GET /members/{id})
	GetMember(w http.ResponseWriter, r *http.Request, id PathID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBooks operation middleware
func (siw *ServerInterfaceWrapper) ListBooks(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBooksParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBooks(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBook operation middleware
func (siw *ServerInterfaceWrapper) CreateBook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBook operation middleware
func (siw *ServerInterfaceWrapper) GetBook(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PathID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBook(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLoans operation middleware
func (siw *ServerInterfaceWrapper) ListLoans(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListLoansParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLoans(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// BorrowBook operation middleware
func (siw *ServerInterfaceWrapper) BorrowBook(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.BorrowBook(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLoan operation middleware
func (siw *ServerInterfaceWrapper) GetLoan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PathID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLoan(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReturnLoan operation middleware
func (siw *ServerInterfaceWrapper) ReturnLoan(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PathID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReturnLoan(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMembersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMembers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMember(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMember operation middleware
func (siw *ServerInterfaceWrapper) GetMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id PathID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMember(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/loans", wrapper.ListLoans)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/loans", wrapper.BorrowBook)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/loans/{id}", wrapper.GetLoan)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/loans/{id}/return", wrapper.ReturnLoan)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/books", wrapper.ListBooks)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/books", wrapper.CreateBook)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/books/{id}", wrapper.GetBook)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/members", wrapper.ListMembers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/members", wrapper.CreateMember)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/members/{id}", wrapper.GetMember)

	return m
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type NotImplementedJSONResponse Error

type UnprocessableEntityJSONResponse Error

type ListBooksRequestObject struct {
	Params ListBooksParams
}

type ListBooksResponseObject interface {
	VisitListBooksResponse(w http.ResponseWriter) error
}

type ListBooks200JSONResponse BookList

func (response ListBooks200JSONResponse) VisitListBooksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListBooks400JSONResponse struct{ BadRequestJSONResponse }

func (response ListBooks400JSONResponse) VisitListBooksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListBooks500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListBooks500JSONResponse) VisitListBooksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListBooks501JSONResponse struct{ NotImplementedJSONResponse }

func (response ListBooks501JSONResponse) VisitListBooksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBookRequestObject struct {
	Body *CreateBookJSONRequestBody
}

type CreateBookResponseObject interface {
	VisitCreateBookResponse(w http.ResponseWriter) error
}

type CreateBook201JSONResponse Book

func (response CreateBook201JSONResponse) VisitCreateBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBook400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateBook400JSONResponse) VisitCreateBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBook500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateBook500JSONResponse) VisitCreateBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateBook501JSONResponse struct{ NotImplementedJSONResponse }

func (response CreateBook501JSONResponse) VisitCreateBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type GetBookRequestObject struct {
	Id PathID `json:"id"`
}

type GetBookResponseObject interface {
	VisitGetBookResponse(w http.ResponseWriter) error
}

type GetBook200JSONResponse Book

func (response GetBook200JSONResponse) VisitGetBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetBook400JSONResponse struct{ BadRequestJSONResponse }

func (response GetBook400JSONResponse) VisitGetBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetBook404JSONResponse struct{ NotFoundJSONResponse }

func (response GetBook404JSONResponse) VisitGetBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetBook500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetBook500JSONResponse) VisitGetBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetBook501JSONResponse struct{ NotImplementedJSONResponse }

func (response GetBook501JSONResponse) VisitGetBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse HealthStatus

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLoansRequestObject struct {
	Params ListLoansParams
}

type ListLoansResponseObject interface {
	VisitListLoansResponse(w http.ResponseWriter) error
}

type ListLoans200JSONResponse LoanList

func (response ListLoans200JSONResponse) VisitListLoansResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListLoans400JSONResponse struct{ BadRequestJSONResponse }

func (response ListLoans400JSONResponse) VisitListLoansResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListLoans500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListLoans500JSONResponse) VisitListLoansResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListLoans501JSONResponse struct{ NotImplementedJSONResponse }

func (response ListLoans501JSONResponse) VisitListLoansResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type BorrowBookRequestObject struct {
	Body *BorrowBookJSONRequestBody
}

type BorrowBookResponseObject interface {
	VisitBorrowBookResponse(w http.ResponseWriter) error
}

type BorrowBook201JSONResponse BorrowResult

func (response BorrowBook201JSONResponse) VisitBorrowBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type BorrowBook400JSONResponse struct{ BadRequestJSONResponse }

func (response BorrowBook400JSONResponse) VisitBorrowBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type BorrowBook404JSONResponse struct{ NotFoundJSONResponse }

func (response BorrowBook404JSONResponse) VisitBorrowBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type BorrowBook409JSONResponse struct{ ConflictJSONResponse }

func (response BorrowBook409JSONResponse) VisitBorrowBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type BorrowBook422JSONResponse struct {
	UnprocessableEntityJSONResponse
}

func (response BorrowBook422JSONResponse) VisitBorrowBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type BorrowBook500JSONResponse struct{ InternalErrorJSONResponse }

func (response BorrowBook500JSONResponse) VisitBorrowBookResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetLoanRequestObject struct {
	Id PathID `json:"id"`
}

type GetLoanResponseObject interface {
	VisitGetLoanResponse(w http.ResponseWriter) error
}

type GetLoan200JSONResponse Loan

func (response GetLoan200JSONResponse) VisitGetLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetLoan400JSONResponse struct{ BadRequestJSONResponse }

func (response GetLoan400JSONResponse) VisitGetLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetLoan404JSONResponse struct{ NotFoundJSONResponse }

func (response GetLoan404JSONResponse) VisitGetLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetLoan500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetLoan500JSONResponse) VisitGetLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetLoan501JSONResponse struct{ NotImplementedJSONResponse }

func (response GetLoan501JSONResponse) VisitGetLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type ReturnLoanRequestObject struct {
	Id PathID `json:"id"`
}

type ReturnLoanResponseObject interface {
	VisitReturnLoanResponse(w http.ResponseWriter) error
}

type ReturnLoan200JSONResponse Loan

func (response ReturnLoan200JSONResponse) VisitReturnLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReturnLoan400JSONResponse struct{ BadRequestJSONResponse }

func (response ReturnLoan400JSONResponse) VisitReturnLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReturnLoan404JSONResponse struct{ NotFoundJSONResponse }

func (response ReturnLoan404JSONResponse) VisitReturnLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReturnLoan409JSONResponse struct{ ConflictJSONResponse }

func (response ReturnLoan409JSONResponse) VisitReturnLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ReturnLoan500JSONResponse struct{ InternalErrorJSONResponse }

func (response ReturnLoan500JSONResponse) VisitReturnLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReturnLoan501JSONResponse struct{ NotImplementedJSONResponse }

func (response ReturnLoan501JSONResponse) VisitReturnLoanResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type ListMembersRequestObject struct {
	Params ListMembersParams
}

type ListMembersResponseObject interface {
	VisitListMembersResponse(w http.ResponseWriter) error
}

type ListMembers200JSONResponse MemberList

func (response ListMembers200JSONResponse) VisitListMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListMembers400JSONResponse struct{ BadRequestJSONResponse }

func (response ListMembers400JSONResponse) VisitListMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListMembers500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListMembers500JSONResponse) VisitListMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListMembers501JSONResponse struct{ NotImplementedJSONResponse }

func (response ListMembers501JSONResponse) VisitListMembersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMemberRequestObject struct {
	Body *CreateMemberJSONRequestBody
}

type CreateMemberResponseObject interface {
	VisitCreateMemberResponse(w http.ResponseWriter) error
}

type CreateMember201JSONResponse Member

func (response CreateMember201JSONResponse) VisitCreateMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMember400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateMember400JSONResponse) VisitCreateMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMember500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateMember500JSONResponse) VisitCreateMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateMember501JSONResponse struct{ NotImplementedJSONResponse }

func (response CreateMember501JSONResponse) VisitCreateMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type GetMemberRequestObject struct {
	Id PathID `json:"id"`
}

type GetMemberResponseObject interface {
	VisitGetMemberResponse(w http.ResponseWriter) error
}

type GetMember200JSONResponse Member

func (response GetMember200JSONResponse) VisitGetMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMember400JSONResponse struct{ BadRequestJSONResponse }

func (response GetMember400JSONResponse) VisitGetMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetMember404JSONResponse struct{ NotFoundJSONResponse }

func (response GetMember404JSONResponse) VisitGetMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetMember500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMember500JSONResponse) VisitGetMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMember501JSONResponse struct{ NotImplementedJSONResponse }

func (response GetMember501JSONResponse) VisitGetMemberResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListBooks List Books
	// (GET /books)
	ListBooks(ctx context.Context, request ListBooksRequestObject) (ListBooksResponseObject, error)
	// CreateBook Create a Book
	// (POST /books)
	CreateBook(ctx context.Context, request CreateBookRequestObject) (CreateBookResponseObject, error)
	// GetBook Get a Book by identifier
	// (GET /books/{id})
	GetBook(ctx context.Context, request GetBookRequestObject) (GetBookResponseObject, error)
	// Healthz Liveness probe
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// ListLoans List Loans
	// (GET /loans)
	ListLoans(ctx context.Context, request ListLoansRequestObject) (ListLoansResponseObject, error)
	// BorrowBook Borrow a Book
	// (POST /loans)
	BorrowBook(ctx context.Context, request BorrowBookRequestObject) (BorrowBookResponseObject, error)
	// GetLoan Get a Loan by identifier
	// (GET /loans/{id})
	GetLoan(ctx context.Context, request GetLoanRequestObject) (GetLoanResponseObject, error)
	// ReturnLoan Return a Loan
	// (POST /loans/{id}/return)
	ReturnLoan(ctx context.Context, request ReturnLoanRequestObject) (ReturnLoanResponseObject, error)
	// ListMembers List Members
	// (GET /members)
	ListMembers(ctx context.Context, request ListMembersRequestObject) (ListMembersResponseObject, error)
	// CreateMember Create a Member
	// (POST /members)
	CreateMember(ctx context.Context, request CreateMemberRequestObject) (CreateMemberResponseObject, error)
	// GetMember Get a Member by identifier
	// (GET /members/{id})
	GetMember(ctx context.Context, request GetMemberRequestObject) (GetMemberResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListBooks operation middleware
func (sh *strictHandler) ListBooks(w http.ResponseWriter, r *http.Request, params ListBooksParams) {
	var request ListBooksRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListBooks(ctx, request.(ListBooksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListBooks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListBooksResponseObject); ok {
		if err := validResponse.VisitListBooksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateBook operation middleware
func (sh *strictHandler) CreateBook(w http.ResponseWriter, r *http.Request) {
	var request CreateBookRequestObject

	var body CreateBookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateBook(ctx, request.(CreateBookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateBook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateBookResponseObject); ok {
		if err := validResponse.VisitCreateBookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetBook operation middleware
func (sh *strictHandler) GetBook(w http.ResponseWriter, r *http.Request, id PathID) {
	var request GetBookRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBook(ctx, request.(GetBookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBookResponseObject); ok {
		if err := validResponse.VisitGetBookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListLoans operation middleware
func (sh *strictHandler) ListLoans(w http.ResponseWriter, r *http.Request, params ListLoansParams) {
	var request ListLoansRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListLoans(ctx, request.(ListLoansRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListLoans")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListLoansResponseObject); ok {
		if err := validResponse.VisitListLoansResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// BorrowBook operation middleware
func (sh *strictHandler) BorrowBook(w http.ResponseWriter, r *http.Request) {
	var request BorrowBookRequestObject

	var body BorrowBookJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.BorrowBook(ctx, request.(BorrowBookRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BorrowBook")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(BorrowBookResponseObject); ok {
		if err := validResponse.VisitBorrowBookResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLoan operation middleware
func (sh *strictHandler) GetLoan(w http.ResponseWriter, r *http.Request, id PathID) {
	var request GetLoanRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLoan(ctx, request.(GetLoanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLoan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLoanResponseObject); ok {
		if err := validResponse.VisitGetLoanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReturnLoan operation middleware
func (sh *strictHandler) ReturnLoan(w http.ResponseWriter, r *http.Request, id PathID) {
	var request ReturnLoanRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReturnLoan(ctx, request.(ReturnLoanRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReturnLoan")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReturnLoanResponseObject); ok {
		if err := validResponse.VisitReturnLoanResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListMembers operation middleware
func (sh *strictHandler) ListMembers(w http.ResponseWriter, r *http.Request, params ListMembersParams) {
	var request ListMembersRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListMembers(ctx, request.(ListMembersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMembers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListMembersResponseObject); ok {
		if err := validResponse.VisitListMembersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateMember operation middleware
func (sh *strictHandler) CreateMember(w http.ResponseWriter, r *http.Request) {
	var request CreateMemberRequestObject

	var body CreateMemberJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateMember(ctx, request.(CreateMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateMember")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateMemberResponseObject); ok {
		if err := validResponse.VisitCreateMemberResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMember operation middleware
func (sh *strictHandler) GetMember(w http.ResponseWriter, r *http.Request, id PathID) {
	var request GetMemberRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMember(ctx, request.(GetMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMember")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMemberResponseObject); ok {
		if err := validResponse.VisitGetMemberResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5FpRb9s4Ev4rA94BtwuosZPtPpz71Ov22gDZbbGb4h6KIqClscWtRKrkKLav8H8/DEnJcixZ6V6SNrsv",
	"gW2RnOF8M/PNjPJZpKasjEZNTsw+i0paWSKh9d9e1NYZy58ydKlVFSmjxUy8qeSnGiH1j8Ei1VZjBvMN",
	"SKgsXitTO6jkEkE60Limq7D0RCRC8QGfarQbkQgtSxQzEZ6KRLg0x1KyQNpU/MSRVXoptttEXKhS0aEu",
	"P8u1KusSdF3O0YJZgCIsHZCJioHSYDR6fYYUKPzZXfkZLmRdkJidTRNRBhlidjrlb0rHb0mjptKES7Re",
	"z7eS8vOfDhW9zBEsOlPbFEFlqEktFFr47t2785++bzWrJOU7xVQmEmHxU60sZmJGtsaulgtjS0liJura",
	"r7xptS1vdpXRDj2g/5LZr/ipRucNmRpNqP1HWVWFSiWrOvndsb6fO2L+bnEhZuJvk52zTMJTN3lprbFB",
	"VN99vTBYSQelLFhdzMBYuFamkIQZUI7AeliZ0onYJuKF0YtCpQ+sYBqlOlgpyoNWtbWoaYeZI0nodTzX",
	"hFbLIhx974o+11BrXFeYssUc2mu0gLzaa/OLoX+bWmcPajHMdobJDDrQhgDXylGj03lZFViiJnwgzUyF",
	"1h8KykGGaSEtJ6WavG4bJFA7lbyW73RlTYrOyXmBLzUp2jx8XKywKJ7EyGBlJRSoM6WXYOuCly5qhxko",
	"Nuy2Cf4QzcZ89Enb8tVJhRiX11IVfKHDFPSfHClH692bN7OhopsXG1hYRE6bc2OtWZ3s0sncmAKlZoup",
	"7BZpJxGkKMg/TOO7ZPY+ZLewNuno/aE90cx/x5T4RFb3QoW8tX/fTJIHw6f9MVS8ybbt+dJaueHvHZI6",
	"NFugQViYYDle69kk4Uym66KAVY4acJ3L2nnfSgT/HEAIOfu4Ifwd9rXoNwIj08ng+5aYG/PxKiB06HIe",
	"7z10R1EskSl18MSf/eN4IPtr41a3OPzG/RvNuzKPGcB5aj7whBqvMknYr67SjqQmrlJWuUrzXRSUtSOY",
	"Y1vI7OnPBz4hVWKfhQoj9aB9OhxvFtFzVsUGUoue+i6M1B32P26hRlKyu2WfgV74s/lWg15yy9gMy4Zl",
	"BPQHpYT6ZUyIX9Uno2XWQ7M6pZcFBv4Dl8sK+a8N9Sdeo92ANvrJ2XoNTe3D5t1XD/vPfw55XUr9xKLM",
	"OHqh85hBXOWSYMVVwcoavRyHLcjpu+FrlAXlv5Gk2h2az7W/41oya/Hej6Pi4rY+eextR1PGaDoIgY7Z",
	"laS99UcjpBuTt9txS232ktPo6ia0o+4HtKh9fPqIZE5ulj9r0rsquP5TRQEyJXWNgyniy/K+V7Yv+e1b",
	"eyToWe074EbvIePceC/MFrJJTzHjrX3F2c8dY6F/tIVMBOiJxzI1taZOlLZ92q3dbCCPJZ0IPWbToJ3L",
	"VRUjvdcDvJD2yGT/1sPmugPMo92/Kuod6wxWrLKpNvYqVuZXKriL7NY1qLk5fx+t6Pvq+PFDb4es9ML0",
	"+1ZTiM+5vcLMN6q4phmscgOl3EShsZ6o8o1TqSx8UeFA6gx4mw2swcW8O4HLnJsTk9bchvBtaEdpsZ3i",
	"YsHWlLcF5+vLy7dtk/zM//TKNH2gcrBEzZ0PZrCwpuROAd7oYgOhWoLv3r757RIm3pu+92rxCYW6Ro3O",
	"QWXNHEFahBXDB2QyuXkWmdR46w93ViFROvhxegq/GIJO0we1JlWAIgeuUCny3nmtihCPoQgRF9HCz9+e",
	"i0Rco3XB+qcn05Mpu4ipUMtKiZn44WR68gMTuaTce8qEE6f/tEQfB62a5xkfrRx5JPye3VjrfX9E7JZM",
	"wqRpm4wujPOx7YcbY5az6fTO+si28ekbDIQhm1kEl/M97dMgu+/IVsdJZw60TcSPt9myP/Pwu07Hd92Y",
	"A/gGti5LaTcRIWggIrl0TSvgxIdtIirjemDdVbhxMoYMc3Z3jfthCb3dT2+cALcHiJ/eKeJDgwPfr3CF",
	"EpuIxwZ5MC5IiADeRH2bxLCefFbZdjC2XyHFA74ssuNs9t4Ddnx4FvrkPwbe0+nTW8EQpoJfEe1XSBFq",
	"7s12/fAA8Llvif47iPrr+PwewdvrygZAZOKNfFb4VuBmVusSa+eqpmou2pazg8R14Vc8auJqu5KjxOUv",
	"+iiJq4GogTdW6x3iunnnWMKS/IiuiQujgTcmIaFzKSRB4yp2MV4I10v7HhIKu3vkwP1B44PzX2fIN8aD",
	"TZv8LNqtbeH/T4L84hz7dPrP8Q3tyy3ecHY2vqHvDcUfdPw9D46twQEPN07cZqlRHvZTg2+Rh8M4Y4yH",
	"Q4D9JXjYh8YQD/cDPwn9nR8y9Ca1lzoDqbvZCiS3voBrxk1ReGsKZKV2ijdxCxzjd46pKTkVNm9+QC6l",
	"0nHc1g7kLKbGZky3FkkqjRnLyJUjYzeHyfFXr/KjdMuD+eO3m72+lisHdKM3D/hvGKMeL7Di6Olxl1id",
	"MeDRIite9lGWWTugGqgbeMdmBHG2eZ9Tgv2XYA9cJzWz2/5cEovNP8OsoAXy0AM64T5aqbTHfHukcBzK",
	"XbUS1v1F6pXm/wsGKpaOE2y3/wsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
